---
- name: 系统初始化---关闭swap
  lineinfile:
    dest: /etc/fstab
    regexp: ".*swap"
    line: ""

- name: 系统初始化---关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: 系统初始化---关闭firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: 系统初始化---即时生效
  shell: setenforce 0 ; swapoff -a

- name: 系统初始化---拷贝时区
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime

- name: 系统初始化---添加hosts
  template: src=hosts.j2 dest=/etc/hosts
  tags: sys_set_host_info


# yum -y install ntp ntpdate
# 设置系统时间与网络时间同步(可以选择time.nist.gov、time.nuri.net、0.asia.pool.ntp.org、1.asia.pool.ntp.org、2.asia.pool.ntp.org、3.asia.pool.ntp.org中任意一个)
# ntpdate -u ntp1.aliyun.com
# 将系统时间写入硬件时间  hwclock --systohc

- name: 系统初始化---安装同步系统时间工具
  yum: name=ntpdate state=present
  ignore_errors: true

- name: 系统初始化---同步阿里云时间
  shell: |
    ntpdate ntp1.aliyun.com
  ignore_errors: yes

- name: 安装环境变量
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - curl
      - gcc
      - openssl-devel
      - libnl3-devel
      - net-snmp-devel
      - ceph-common
      - net-tools
      - epel-release
      - git
      - lrzsz
      - wget
      - vim
      - gcc-c++
      - libjpeg
      - libjpeg-devel
      - libpng
      - libpng-devel
      - freetype
      - freetype-devel
      - libxml2
      - libxml2-devel
      - zlib
      - zlib-devel
      - curl-devel
      - ncurses
      - ncurses-devel
      - tree
      - bash-completion
    state: present
  ignore_errors: yes
  tags: sys_set,sys_set_env


