---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: prometheus-etcd-metrics
  labels:
    app.kubernetes.io/name: prometheus-etcd-metrics
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: etcd-https-metrics
      port: 2379
      protocol: TCP
      targetPort: 2379
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/name: prometheus-etcd-metrics
  name: prometheus-etcd-metrics
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.0.211
      - ip: 192.168.0.212
      - ip: 192.168.0.213
    ports:
      - name: etcd-https-metrics
        port: 2379
        protocol: TCP

