- name: 在节点创建相关目录
  file: name={{ item }} state=directory
  with_items:
    - /etc/cni/net.d
    - /etc/calico/ssl
    - /etc/calico/yml

#- name: 分发calico证书相关
#  copy: src=etcd_cert/{{ item }} dest=/etc/calico/ssl/{{ item }} mode=0755
#  with_items:
#  - ca.pem
#  - server.pem
#  - server-key.pem

#- name: get calico-etcd-secrets info
#  shell: |
#    /usr/bin/kubectl get secrets -n kube-system
#  register: secrets_info
#  run_once: true
#
#- name: 创建 calico-etcd-secrets
#  shell: |
#    cd /etc/calico/ssl && \
#    /usr/bin/kubectl create secret generic -n kube-system calico-etcd-secrets \
#    --from-file=etcd-ca=ca.pem \
#    --from-file=etcd-key=server-key.pem \
#    --from-file=etcd-cert=server.pem
#  when: '"calico-etcd-secrets" not in secrets_info.stdout'
#  run_once: true

- name: 配置 calico DaemonSet yaml文件
#  template: src=calico-v3.15.yaml.j2 dest=/etc/calico/yml/calico.yaml mode=0755
  copy: src=calico.yaml dest=/etc/calico/yml/calico.yaml mode=0755
#  run_once: true


- name: 清除calico网络
  shell: |
    /usr/bin/kubectl delete -f /etc/calico/yml/calico.yaml
  run_once: true
  ignore_errors: true
  
# 只需单节点执行一次
- name: 运行 calico网络
  shell: |
    /usr/bin/kubectl apply -f /etc/calico/yml/calico.yaml
  run_once: true
  ignore_errors: true

# 删除原有cni配置
- name: 删除默认cni配置
  file: path=/etc/cni/net.d/10-default.conf state=absent

# 等待网络插件部署成功，视下载镜像速度而定
- name: 轮询等待calico-node 运行，视下载镜像速度而定
  shell: |
    /usr/bin/kubectl get pod -n kube-system -o wide|grep 'calico-node' | awk '{print $3}' | awk 'NR==1{print}'
  register: pod_status
  until: pod_status.stdout == "Running"
  retries: 15
  delay: 60
  ignore_errors: true
