---
apiVersion: v1
kind: Service
metadata:
  namespace:  ingress-nginx
  name: ingress-metrics
  labels:
    app.kubernetes.io/name: ingress-metrics
#  annotations:
#    prometheus.io/scrape: "true"
#    prometheus.io/port: "10254"
spec:
  type: ClusterIP
  ports:
    - name: ingress-metrics
      port: 10254
      protocol: TCP
      targetPort: 10254
  selector:
    app.kubernetes.io/name: ingress-nginx
#---
#apiVersion: v1
#kind: Endpoints
#metadata:
#  labels:
#    app.kubernetes.io/name: prometheus-ing-metrics
#  name: prometheus-ing-metrics
#  namespace: ingress-nginx
#subsets:
#  - addresses:
#      - ip: 192.168.0.46
#      - ip: 192.168.0.47
#      - ip: 192.168.0.48
#    ports:
#      - name: ing-http-metrics
#        port: 10254
#        protocol: TCP

