---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: singleton-redis-pvc     #pvc名称
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany     #访问模式
  resources:
    requests:
      storage: 2Gi      #存储空间 必须为10Gi以上 否则绑定失败创建PV失败
  storageClassName: singleton-redis-sc   #后端storageclass名称