apiVersion: v1
kind: ConfigMap
metadata:
  name: singleton-redis-conf
  namespace: devops
  labels:
    app: singleton-redis
data:
  redis.conf: |
    dir /data
    port 6379
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    requirepass www123
    pidfile /data/redis-6379.pid
