---
- name: ingress---创建目录
  file: name=/opt/kubernetes/yml/ingress state=directory
  tags: ingress_cfg

- name: ingree---分发yml文件
  copy: src=deploy-1.1.1.yaml dest=/opt/kubernetes/yml/ingress/deploy.yaml mode=0755
  tags: ingress_cfg

# 如果卸载失败
# kubectl proxy
# 新开窗口
#  cd /tmp
#  kubectl get namespace ingress-nginx -o json > ingress.json
#  删除spec 中的元素
#  sed -i '/"finalizers"/{n;d}' ingress.json
# curl -k -H "Content-Type: application/json" -X PUT --data-binary @ingress.json http://127.0.0.1:8001/api/v1/namespaces/ingress-nginx/finalize
#
#- name: ingress---卸载ingress
#  shell: |
#    /usr/bin/kubectl delete -f /opt/kubernetes/yml/ingress/deploy.yaml
#  run_once: true
#  ignore_errors: true



# 修改配置文件 303行  由  Deployment--》DaemonSet
#  nodeSelector添加 ingress: "true"
# 设置node 表签 kubectl label node node-3 ingress=true

- name: 为node-1添加标签 ingres=true
  shell:
    cmd: "/usr/bin/kubectl label nodes k8s-node-1 k8s-node-2 k8s-node-3 ingress=true"
  run_once: true
  ignore_errors: yes

- name: ingress---部署ingress
  shell: |
    /usr/bin/kubectl apply -f /opt/kubernetes/yml/ingress/deploy.yaml
  run_once: true

- name: ingress---查看Pod状态
  shell: | 
    kubectl get po --all-namespaces -owide
  register: getall
- debug: var=getall.stdout_lines