---
apiVersion: v1
kind: Namespace
metadata:
  name: test

---
apiVersion: v1
kind: Secret
metadata:
  name: static-ceph-secret
  namespace: test
data:
  key: QVFCRGQ1Vmk3ZC9SQnhBQTkrSGhmMGZBRGpNNG9jcnRXWjdVbWc9PQ==