apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-ceph-pv
  namespace: test
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  rbd:
    monitors:
      - 192.168.0.46:6789
      - 192.168.0.47:6789
      - 192.168.0.48:6789
    pool: rbd
    image: image01
    user: admin
    secretRef:
      name: static-ceph-secret
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
