---
- name: docker---创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: docker---分发并解压docker二进制包
  unarchive: src={{ item }} dest={{ tmp_dir }}
  with_fileglob:
    - "{{ software_dir }}/docker-*.tgz"

- name: 创建docker用户
  shell: |
    useradd docker
  ignore_errors: yes

- name: docker---移动docker二进制文件
  shell: cp -rf {{ tmp_dir }}/docker/* /usr/bin

- name: docker---分发service文件
  copy: src=docker.service dest=/usr/lib/systemd/system/

- name: docker---创建目录
  file: dest=/etc/docker state=directory

- name: docker---配置docker
  copy: src=daemon.json dest=/etc/docker/daemon.json

- name: docker---检查docker是否启动
  ansible.builtin.systemd:
    name: docker
  register: check_docker_status
  tags: check_docker_status

- name: docker---启动docker
  systemd: name=docker state=started enabled=yes daemon_reload=yes
  when: check_docker_status.status.ActiveState == 'inactive' or check_docker_status.status.ActiveState == 'failed'

- name: docker---重启docker
  systemd: name=docker state=restarted enabled=yes daemon_reload=yes
  when: check_docker_status.status.ActiveState == 'active'

- name: docker---查看状态
  shell: docker info
  register: docker 
- debug: var=docker.stdout_lines
