apiVersion: v1
kind: Service
metadata:
  name: singleton-pgsql
  namespace: devops
spec:
  selector:
    app: singleton-pgsql
  ports:
    - port: 35432
      targetPort: 5432
      nodePort: 35432
  type: NodePort