---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-rbd-pvc-01     #pvc名称
  namespace: ceph-csi
spec:
  accessModes:
    #(RWO）ReadWriteOnce         存储可读可写，但只支持被单个 Pod挂载
    #(ROX）ReadonlyMany          存储可以以只读的方式被多个Pod 挂载
    #(RWX）ReadwriteMany         存储可以以读写的方式被多个Pod 共享
    - ReadWriteOnce     #访问模式
  volumeMode: Filesystem     #数据卷类型 Filesystem Block
  resources:
    requests:
      storage: 200Mi      #存储空间 必须为10Gi以上 否则绑定失败创建PV失败
  storageClassName: csi-rbd-sc   #后端storageclass名称