# 源数据： AQBDd5Vi7d/RBxAA9+Hhf0fADjM4ocrtWZ7Umg==
# base64编码: QVFCRGQ1Vmk3ZC9SQnhBQTkrSGhmMGZBRGpNNG9jcnRXWjdVbWc9PQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: ceph-csi
stringData:
  userID: admin
  userKey: AQA7MQNjf30jFRAAFahDfPtyY1EErAUqCZuApQ==