---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cephfs-pvc-test     #pvc名称
  namespace: cephfs-csi
#  annotations:
#    pv.kubernetes.io/bind-completed: 'yes'
#    pv.kubernetes.io/bound-by-controller: 'yes'
#    volume.beta.kubernetes.io/storage-provisioner: rbd.csi.ceph.com
spec:
  accessModes:
    - ReadWriteMany     #访问模式
#  volumeMode: Filesystem     #数据卷类型 Filesystem Block
  resources:
    requests:
      storage: 200Mi      #存储空间 必须为10Gi以上 否则绑定失败创建PV失败
  storageClassName: csi-cephfs-sc   #后端storageclass名称